object_type: bathing_place
label: "Badplatser"
qid: Q567998  # Bathing place (Swimming facility)

wikidata:
  sparql_query: |
    SELECT ?item ?coord ?country ?division ?badkartan WHERE {
      ?item wdt:P31 wd:Q567998 .
      ?item wdt:P625 ?coord .
      ?item wdt:P17 ?country .
      ?item wdt:P131 ?division .
      OPTIONAL { ?item wdt:P9615 ?badkartan }
      MINUS { ?item wdt:P10689 [] } # way
      MINUS { ?item wdt:P402 [] } # rel
      MINUS { ?item wdt:P11693 [] } # node
    }
  label_property: itemLabel
  coord_property: coord
  node_property: P11693
  way_property: P10689
  relation_property: P402
  not_found_property: P9660
  not_found_qualifier: P5017

overpass:
  query: |
    [out:json][timeout:10];
    (
      nwr["leisure"="bathing_place"]({{bbox}});
      nwr["natural"="beach"]({{bbox}});
      nwr["sport"="swimming"]({{bbox}});
    );
    out body center;
  bbox_from_coord: true
  bbox_radius_km: 0.5
  timeout: 10

matching:
  method: bbox
  similarity_threshold: 0.25
  exclude_words:
    - "badplats"
    - "strand"
    - "bathing"
    - "beach"
